version: 2.1

jobs:
  v2ex:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi
      - run:
          name: Run V2EX signin
          command: |
            python -m v2ex.v2ex

workflows:
  version: 2
  daily_actions:
    triggers:
      - schedule:
          cron: "0 23 * * *"  # UTC 09:00 (Beijing 17:00)
          filters:
            branches:
              only:
                - main
    jobs:
      - v2ex:
          context: checkincontext
  
  # Allow manual triggers
  manual_trigger:
    jobs:
      - v2ex:
          context: checkincontext
